### ISSUE TITLE
运行createlmdb时出现error: (-10:Unknown error code -10) Raw image encoder error:

### ISSUE THREAD

**Issue by PengJingchao** [HonglinChu/SiamRPN#2]
你好，我在用你上传到百度网盘的dataset运行createlmdb程序时出现下面的错误：
 34%|███▍      | 61506/178514 [18:51<35:53, 54.34it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/pjc/MyProgram/RPN/bin/create_lmdb.py", line 22, in worker
    _, img_encode = cv2.imencode('.jpg', img)
cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/imgcodecs/src/grfmt_base.cpp:145: error: (-10:Unknown error code -10) Raw image encoder error: Empty JPEG image (DNL not supported) in function 'throwOnEror'

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pjc/MyProgram/RPN/bin/create_lmdb.py", line 51, in <module>
    create_lmdb(args.data_dir,args.output_dir,args.num_thread)
  File "/home/pjc/MyProgram/RPN/bin/create_lmdb.py", line 33, in create_lmdb
    for ret in tqdm(pool.imap_unordered(functools.partial(worker), video_names), total=len(video_names)):
  File "/usr/local/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/usr/local/anaconda3/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/imgcodecs/src/grfmt_base.cpp:145: error: (-10:Unknown error code -10) Raw image encoder error: Empty JPEG image (DNL not supported) in function 'throwOnEror'

可能是数据压缩包上传或下载解压时有错误导致传入图片为空，能不能麻烦你提供下youytube-bb原始数据集？我重新运行下createdataset，谢谢！

**Comment by HonglinChu** [comment]
那个数据应该是没有问题，好像是要在windows下解压，linux下不行，去年训练的。如果还有问题可以添加我github上 --&gt; 项目 SiamTrackers --&gt; readme --&gt;siamTrackers微信群二维码，加入群里讨论。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"PengJingchao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 下午4:31
收件人:&nbsp;"HonglinChu/SiamRPN"<SiamRPN@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HonglinChu/SiamRPN] 运行createlmdb时出现error: (-10:Unknown error code -10) Raw image encoder error: (#2)





 
你好，我在用你上传到百度网盘的dataset运行createlmdb程序时出现下面的错误：
 34%|███▍      | 61506/178514 [18:51<35:53, 54.34it/s]
 multiprocessing.pool.RemoteTraceback:
 """
 Traceback (most recent call last):
 File "/usr/local/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
 result = (True, func(*args, **kwds))
 File "/home/pjc/MyProgram/RPN/bin/create_lmdb.py", line 22, in worker
 _, img_encode = cv2.imencode('.jpg', img)
 cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/imgcodecs/src/grfmt_base.cpp:145: error: (-10:Unknown error code -10) Raw image encoder error: Empty JPEG image (DNL not supported) in function 'throwOnEror'
 
"""
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
 File "/home/pjc/MyProgram/RPN/bin/create_lmdb.py", line 51, in 
 create_lmdb(args.data_dir,args.output_dir,args.num_thread)
 File "/home/pjc/MyProgram/RPN/bin/create_lmdb.py", line 33, in create_lmdb
 for ret in tqdm(pool.imap_unordered(functools.partial(worker), video_names), total=len(video_names)):
 File "/usr/local/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 1129, in iter
 for obj in iterable:
 File "/usr/local/anaconda3/lib/python3.7/multiprocessing/pool.py", line 748, in next
 raise value
 cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/imgcodecs/src/grfmt_base.cpp:145: error: (-10:Unknown error code -10) Raw image encoder error: Empty JPEG image (DNL not supported) in function 'throwOnEror'
 
可能是数据压缩包上传或下载解压时有错误导致传入图片为空，能不能麻烦你提供下youytube-bb原始数据集？我重新运行下createdataset，谢谢！

**Comment by PengJingchao** [comment]
好的，谢谢！
